# action.yml
name: "delete-stale-branch"
description: "Delete branches which are older than certain period of time"
inputs:
  repo_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  date:
    description: "A git-log compatible date format"
    required: true
  dry_run:
    description: "Run in dry-run mode so no branches are deleted"
    required: false
    default: true
  delete_tags:
    description: "Also look for tags to delete"
    required: false
    default: false
  minimum_tags:
    description: "Minimum number of tags to keep"
    required: false
    default: false
  default_branches:
    description: "Default branch(es) to exclude"
    required: false
    default: main,master
  extra_protected_branch_regex:
    description: "grep extended (ERE) compatible regex for additional branches to exclude"
    required: false
  extra_protected_tag_regex:
    description: "grep extended (ERE) compatible regex for additional tags to exclude"
    required: false
  exclude_open_pr_branches:
    description: "Exclude branches that have an open pull request"
    required: false
    default: true
outputs:
  was_dry_run:
    description: "Ran in dry-run mode so no branches were deleted"
  deleted_branches:
    description: "List of branches that were deleted"
runs:
  using: "composite"
  steps:
    - run: | 
        export INPUT_REPO_TOKEN=${{ inputs.repo_token }};
        export INPUT_DATE=${{ inputs.date }};
        ${{ github.action_path }}/delete-old-branches.sh \
          "${{ inputs.repo_token }}" \
          "${{ inputs.date }}" \
          "${{ inputs.dry_run }}" \
          "${{ inputs.delete_tags }}" \
          "${{ inputs.minimum_tags }}" \
          "${{ inputs.default_branches }}" \
          "${{ inputs.extra_protected_branch_regex }}" \
          "${{ inputs.extra_protected_tag_regex }}" \
          "${{ inputs.exclude_open_pr_branches }}"
      shell: bash
